-- ===================== TABLES ============================

-- Lead Sources Table
CREATE TABLE IF NOT EXISTS public.lead_sources (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    file_name TEXT,
    last_imported TIMESTAMPTZ,
    record_count INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    metadata JSONB,
    storage_path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  website TEXT,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- Leads Table
CREATE TABLE IF NOT EXISTS public.leads (
  id uuid not null default extensions.uuid_generate_v4 (),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  status text not null default 'NEW'::text,
  lead_source_id uuid null,
  assigned_to uuid null,
  notes text null,
  last_contacted_at timestamp with time zone null,
  raw_lead_table text null,
  raw_lead_id text null,
  contact1_name text null,
  contact1_email_1 text null,
  contact2_name text null,
  contact2_email_1 text null,
  property_address text null,
  property_city text null,
  property_state text null,
  property_postal_code text null,
  property_type text null,
  baths text null,
  beds text null,
  year_built text null,
  square_footage text null,
  wholesale_value text null,
  assessed_total text null,
  mls_curr_status text null,
  mls_curr_days_on_market text null,
  avm text null,
  source_id text null,
  address_hash text null,
  airconditioning text null,
  first_name text null,
  last_name text null,
  recipient_address text null,
  recipient_city text null,
  recipient_state text null,
  recipient_postal_code text null,
  county text null,
  owner_type text null,
  last_sales_date text null,
  last_sales_price text null,
  price_per_sqft text null,
  lot_size_sqft text null,
  contact1_phone_1 text null,
  contact1_phone_1_type text null,
  contact1_phone_1_dnc text null,
  contact1_phone_1_litigator text null,
  contact1_phone_2 text null,
  contact1_phone_2_type text null,
  contact1_phone_2_dnc text null,
  contact1_phone_2_litigator text null,
  contact1_phone_3 text null,
  contact1_phone_3_type text null,
  contact1_phone_3_dnc text null,
  contact1_phone_3_litigator text null,
  contact1_email_2 text null,
  contact1_email_3 text null,
  contact2_phone_1 text null,
  contact2_phone_1_type text null,
  contact2_phone_1_dnc text null,
  contact2_phone_1_litigator text null,
  contact2_phone_2 text null,
  contact2_phone_2_type text null,
  contact2_phone_2_dnc text null,
  contact2_phone_2_litigator text null,
  contact2_phone_3 text null,
  contact2_phone_3_type text null,
  contact2_phone_3_dnc text null,
  contact2_phone_3_litigator text null,
  contact2_email_2 text null,
  contact2_email_3 text null,
  contact3_name text null,
  contact3_phone_1 text null,
  contact3_phone_1_type text null,
  contact3_phone_1_dnc text null,
  contact3_phone_1_litigator text null,
  contact3_email_1 text null,
  contact3_phone_2 text null,
  contact3_phone_2_type text null,
  contact3_phone_2_dnc text null,
  contact3_phone_2_litigator text null,
  contact3_email_2 text null,
  contact3_phone_3 text null,
  contact3_phone_3_type text null,
  contact3_phone_3_dnc text null,
  contact3_phone_3_litigator text null,
  contact3_email_3 text null,
  house_style text null,
  assessed_year text null,
  school_district text null,
  stories text null,
  heating_fuel text null,
  subdivision text null,
  zoning text null,
  units text null,
  condition text null,
  exterior text null,
  interior_walls text null,
  basement text null,
  roof text null,
  roof_shape text null,
  water text null,
  sewer text null,
  location_influence text null,
  heating text null,
  air_conditioning text null,
  fireplace text null,
  garage text null,
  patio text null,
  pool text null,
  porch text null,
  tax_amount text null,
  rental_estimate_low text null,
  rental_estimate_high text null,
  market_value text null,
  mls_curr_listing_id text null,
  mls_curr_list_date text null,
  mls_curr_sold_date text null,
  mls_curr_list_price text null,
  mls_curr_sale_price text null,
  mls_curr_description text null,
  mls_curr_source text null,
  mls_curr_list_agent_name text null,
  mls_curr_list_agent_phone text null,
  mls_curr_list_agent_email text null,
  mls_curr_list_agent_office text null,
  mls_curr_price_per_sqft text null,
  mls_curr_sqft text null,
  mls_curr_basement text null,
  mls_curr_lot text null,
  mls_curr_beds text null,
  mls_curr_baths text null,
  mls_curr_garage text null,
  mls_curr_stories text null,
  mls_curr_year_built text null,
  mls_curr_photos text null,
  mls_prev_listing_id text null,
  mls_prev_status text null,
  mls_prev_list_date text null,
  mls_prev_sold_date text null,
  mls_prev_days_on_market text null,
  mls_prev_list_price text null,
  mls_prev_sale_price text null,
  mls_prev_description text null,
  mls_prev_source text null,
  mls_prev_list_agent_name text null,
  mls_prev_list_agent_phone text null,
  mls_prev_list_agent_email text null,
  mls_prev_list_agent_office text null,
  mls_prev_price_per_sqft text null,
  mls_prev_sqft text null,
  mls_prev_basement text null,
  mls_prev_lot text null,
  mls_prev_beds text null,
  mls_prev_baths text null,
  mls_prev_garage text null,
  mls_prev_stories text null,
  mls_prev_year_built text null,
  mls_prev_photos text null,
  constraint leads_pkey primary key (id),
  constraint leads_assigned_to_fkey foreign KEY (assigned_to) references profiles (id) on delete set null,
  constraint leads_lead_source_id_fkey foreign KEY (lead_source_id) references lead_sources (id) on delete set null
) TABLESPACE pg_default;

-- Normalized Leads Table
CREATE TABLE IF NOT EXISTS public.normalized_leads (
    id BIGSERIAL PRIMARY KEY,
    original_lead_id UUID,
    contact_name TEXT,
    contact_email TEXT,
    property_address TEXT,
    property_city TEXT,
    property_state TEXT,
    property_postal_code TEXT,
    property_type TEXT,
    baths TEXT,
    beds TEXT,
    year_built TEXT,
    square_footage TEXT,
    wholesale_value NUMERIC,
    assessed_total NUMERIC,
    mls_curr_status TEXT,
    mls_curr_days_on_market TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Console Log Events Table
CREATE TABLE IF NOT EXISTS public.console_log_events (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    type text NOT NULL CHECK (type IN ('info', 'error', 'success')),
    message text NOT NULL,
    timestamp bigint NOT NULL DEFAULT (extract(epoch from now()) * 1000)::bigint,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    file text,
    status text,
    completed_at timestamptz,
    normalized_at timestamptz,
    PRIMARY KEY (id)
);

-- Processing Status Table
CREATE TABLE IF NOT EXISTS public.processing_status (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    file_name text NOT NULL,
    status text NOT NULL,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
