// Mock for @heroui/react/outline
module.exports = { 
  SearchIcon: () => ({ type: "svg", props: { "data-testid": "search-icon" } }), 
  SortAscendingIcon: () => ({ type: "svg", props: { "data-testid": "sort-asc-icon" } }), 
  SortDescendingIcon: () => ({ type: "svg", props: { "data-testid": "sort-desc-icon" } }), 
  ChevronDownIcon: () => ({ type: "svg", props: { "data-testid": "chevron-down-icon" } }), 
  ChevronUpIcon: () => ({ type: "svg", props: { "data-testid": "chevron-up-icon" } }), 
  ChevronRightIcon: () => ({ type: "svg", props: { "data-testid": "chevron-right-icon" } }), 
  ChevronLeftIcon: () => ({ type: "svg", props: { "data-testid": "chevron-left-icon" } }),
  PlusIcon: () => ({ type: "svg", props: { "data-testid": "plus-icon" } }),
  MinusIcon: () => ({ type: "svg", props: { "data-testid": "minus-icon" } }),
  TrashIcon: () => ({ type: "svg", props: { "data-testid": "trash-icon" } }),
  EditIcon: () => ({ type: "svg", props: { "data-testid": "edit-icon" } }),
  EyeIcon: () => ({ type: "svg", props: { "data-testid": "eye-icon" } }),
  EyeOffIcon: () => ({ type: "svg", props: { "data-testid": "eye-off-icon" } }),
  RefreshIcon: () => ({ type: "svg", props: { "data-testid": "refresh-icon" } }),
  MailIcon: () => ({ type: "svg", props: { "data-testid": "mail-icon" } }),
  DocumentIcon: () => ({ type: "svg", props: { "data-testid": "document-icon" } }),
  PhoneIcon: () => ({ type: "svg", props: { "data-testid": "phone-icon" } }),
  CalendarIcon: () => ({ type: "svg", props: { "data-testid": "calendar-icon" } }),
  UserIcon: () => ({ type: "svg", props: { "data-testid": "user-icon" } }),
  HomeIcon: () => ({ type: "svg", props: { "data-testid": "home-icon" } }),
  ClockIcon: () => ({ type: "svg", props: { "data-testid": "clock-icon" } }),
  CheckIcon: () => ({ type: "svg", props: { "data-testid": "check-icon" } }),
  XIcon: () => ({ type: "svg", props: { "data-testid": "x-icon" } }),
  ExclamationIcon: () => ({ type: "svg", props: { "data-testid": "exclamation-icon" } }),
  DotsHorizontalIcon: () => ({ type: "svg", props: { "data-testid": "dots-horizontal-icon" } }),
  DotsVerticalIcon: () => ({ type: "svg", props: { "data-testid": "dots-vertical-icon" } }),
  FilterIcon: () => ({ type: "svg", props: { "data-testid": "filter-icon" } }),
  ArrowRightIcon: () => ({ type: "svg", props: { "data-testid": "arrow-right-icon" } }),
  ArrowLeftIcon: () => ({ type: "svg", props: { "data-testid": "arrow-left-icon" } }),
  ArrowUpIcon: () => ({ type: "svg", props: { "data-testid": "arrow-up-icon" } }),
  ArrowDownIcon: () => ({ type: "svg", props: { "data-testid": "arrow-down-icon" } }),
  // Additional icons that might be used
  PencilIcon: () => ({ type: "svg", props: { "data-testid": "pencil-icon" } })
};