-- Add columns from CSV header to the leads staging table (using snake_case)

-- Ensure columns are added idempotently
DO $$
BEGIN
    -- Contact Info
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'first_name') THEN ALTER TABLE public.leads ADD COLUMN first_name text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'last_name') THEN ALTER TABLE public.leads ADD COLUMN last_name text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'recipient_address') THEN ALTER TABLE public.leads ADD COLUMN recipient_address text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'recipient_city') THEN ALTER TABLE public.leads ADD COLUMN recipient_city text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'recipient_state') THEN ALTER TABLE public.leads ADD COLUMN recipient_state text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'recipient_postal_code') THEN ALTER TABLE public.leads ADD COLUMN recipient_postal_code text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_name') THEN ALTER TABLE public.leads ADD COLUMN contact1_name text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_1') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_1 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_1_type') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_1_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_1_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_1_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_1_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_1_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_email_1') THEN ALTER TABLE public.leads ADD COLUMN contact1_email_1 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_2') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_2 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_2_type') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_2_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_2_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_2_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_2_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_2_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_email_2') THEN ALTER TABLE public.leads ADD COLUMN contact1_email_2 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_3') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_3 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_3_type') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_3_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_3_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_3_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_phone_3_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact1_phone_3_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact1_email_3') THEN ALTER TABLE public.leads ADD COLUMN contact1_email_3 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_name') THEN ALTER TABLE public.leads ADD COLUMN contact2_name text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_1') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_1 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_1_type') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_1_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_1_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_1_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_1_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_1_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_email_1') THEN ALTER TABLE public.leads ADD COLUMN contact2_email_1 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_2') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_2 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_2_type') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_2_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_2_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_2_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_2_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_2_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_email_2') THEN ALTER TABLE public.leads ADD COLUMN contact2_email_2 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_3') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_3 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_3_type') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_3_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_3_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_3_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_phone_3_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact2_phone_3_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact2_email_3') THEN ALTER TABLE public.leads ADD COLUMN contact2_email_3 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_name') THEN ALTER TABLE public.leads ADD COLUMN contact3_name text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_1') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_1 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_1_type') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_1_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_1_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_1_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_1_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_1_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_email_1') THEN ALTER TABLE public.leads ADD COLUMN contact3_email_1 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_2') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_2 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_2_type') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_2_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_2_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_2_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_2_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_2_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_email_2') THEN ALTER TABLE public.leads ADD COLUMN contact3_email_2 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_3') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_3 text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_3_type') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_3_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_3_dnc') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_3_dnc text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_phone_3_litigator') THEN ALTER TABLE public.leads ADD COLUMN contact3_phone_3_litigator text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'contact3_email_3') THEN ALTER TABLE public.leads ADD COLUMN contact3_email_3 text; END IF;

    -- Property Information
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'property_address') THEN ALTER TABLE public.leads ADD COLUMN property_address text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'property_city') THEN ALTER TABLE public.leads ADD COLUMN property_city text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'property_state') THEN ALTER TABLE public.leads ADD COLUMN property_state text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'property_postal_code') THEN ALTER TABLE public.leads ADD COLUMN property_postal_code text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'county') THEN ALTER TABLE public.leads ADD COLUMN county text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'owner_type') THEN ALTER TABLE public.leads ADD COLUMN owner_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'last_sales_date') THEN ALTER TABLE public.leads ADD COLUMN last_sales_date text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'last_sales_price') THEN ALTER TABLE public.leads ADD COLUMN last_sales_price text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'price_per_sqft') THEN ALTER TABLE public.leads ADD COLUMN price_per_sqft text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'square_footage') THEN ALTER TABLE public.leads ADD COLUMN square_footage text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'lot_size_sqft') THEN ALTER TABLE public.leads ADD COLUMN lot_size_sqft numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'property_type') THEN ALTER TABLE public.leads ADD COLUMN property_type text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'baths') THEN ALTER TABLE public.leads ADD COLUMN baths text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'beds') THEN ALTER TABLE public.leads ADD COLUMN beds text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'house_style') THEN ALTER TABLE public.leads ADD COLUMN house_style text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'year_built') THEN ALTER TABLE public.leads ADD COLUMN year_built text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'assessed_year') THEN ALTER TABLE public.leads ADD COLUMN assessed_year text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'school_district') THEN ALTER TABLE public.leads ADD COLUMN school_district text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'stories') THEN ALTER TABLE public.leads ADD COLUMN stories text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'heating_fuel') THEN ALTER TABLE public.leads ADD COLUMN heating_fuel text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'subdivision') THEN ALTER TABLE public.leads ADD COLUMN subdivision text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'zoning') THEN ALTER TABLE public.leads ADD COLUMN zoning text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'units') THEN ALTER TABLE public.leads ADD COLUMN units text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'condition') THEN ALTER TABLE public.leads ADD COLUMN condition text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'exterior') THEN ALTER TABLE public.leads ADD COLUMN exterior text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'interior_walls') THEN ALTER TABLE public.leads ADD COLUMN interior_walls text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'basement') THEN ALTER TABLE public.leads ADD COLUMN basement text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'roof') THEN ALTER TABLE public.leads ADD COLUMN roof text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'roof_shape') THEN ALTER TABLE public.leads ADD COLUMN roof_shape text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'water') THEN ALTER TABLE public.leads ADD COLUMN water text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'sewer') THEN ALTER TABLE public.leads ADD COLUMN sewer text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'location_influence') THEN ALTER TABLE public.leads ADD COLUMN location_influence text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'heating') THEN ALTER TABLE public.leads ADD COLUMN heating text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'air_conditioning') THEN ALTER TABLE public.leads ADD COLUMN air_conditioning text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'fireplace') THEN ALTER TABLE public.leads ADD COLUMN fireplace text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'garage') THEN ALTER TABLE public.leads ADD COLUMN garage text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'patio') THEN ALTER TABLE public.leads ADD COLUMN patio text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'pool') THEN ALTER TABLE public.leads ADD COLUMN pool text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'porch') THEN ALTER TABLE public.leads ADD COLUMN porch text; END IF;

    -- Financial & Valuation
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'tax_amount') THEN ALTER TABLE public.leads ADD COLUMN tax_amount numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'avm') THEN ALTER TABLE public.leads ADD COLUMN avm numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'rental_estimate_low') THEN ALTER TABLE public.leads ADD COLUMN rental_estimate_low text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'rental_estimate_high') THEN ALTER TABLE public.leads ADD COLUMN rental_estimate_high text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'wholesale_value') THEN ALTER TABLE public.leads ADD COLUMN wholesale_value numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'market_value') THEN ALTER TABLE public.leads ADD COLUMN market_value numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'assessed_total') THEN ALTER TABLE public.leads ADD COLUMN assessed_total numeric; END IF;

    -- Event & MLS
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'event') THEN ALTER TABLE public.leads ADD COLUMN event text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_listing_id') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_listing_id text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_status') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_status text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_list_date') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_list_date text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_sold_date') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_sold_date text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_days_on_market') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_days_on_market text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_list_price') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_list_price numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_sale_price') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_sale_price numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_description') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_description text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_source') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_source text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_list_agent_name') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_list_agent_name text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_list_agent_phone') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_list_agent_phone text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_list_agent_email') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_list_agent_email text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_list_agent_office') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_list_agent_office text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_price_per_sqft') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_price_per_sqft numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_sqft') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_sqft numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_basement') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_basement text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_lot') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_lot numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_beds') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_beds text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_baths') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_baths text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_garage') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_garage text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_stories') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_stories text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_year_built') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_year_built text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_curr_photos') THEN ALTER TABLE public.leads ADD COLUMN mls_curr_photos text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_listing_id') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_listing_id text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_status') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_status text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_list_date') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_list_date text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_sold_date') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_sold_date text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_days_on_market') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_days_on_market text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_list_price') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_list_price numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_sale_price') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_sale_price numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_description') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_description text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_source') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_source text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_list_agent_name') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_list_agent_name text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_list_agent_phone') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_list_agent_phone text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_list_agent_email') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_list_agent_email text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_list_agent_office') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_list_agent_office text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_price_per_sqft') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_price_per_sqft numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_sqft') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_sqft numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_basement') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_basement text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_lot') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_lot numeric; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_beds') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_beds text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_baths') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_baths text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_garage') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_garage text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_stories') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_stories text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_year_built') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_year_built text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'mls_prev_photos') THEN ALTER TABLE public.leads ADD COLUMN mls_prev_photos text; END IF;

    -- Flags & Scores
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'absentee_owner') THEN ALTER TABLE public.leads ADD COLUMN absentee_owner text; END IF;
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'active_investor_owned') THEN ALTER TABLE public.leads ADD COLUMN active_investor_owned text; END IF;

    -- Source & Hash
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'source_id') THEN ALTER TABLE public.leads ADD COLUMN source_id text; END IF; -- Renamed from 'Id'
    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'leads' AND column_name = 'address_hash') THEN ALTER TABLE public.leads ADD COLUMN address_hash text; END IF;

END $$;